
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Dec 25 15:42:13 CST 2025
//----------------------------------------------------

import java_cup.runtime.*;

/** CUP v0.11b beta 20140220 generated parser.
  * @version Thu Dec 25 15:42:13 CST 2025
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\011\000\002\003\004\000\002\002\004\000\002\003" +
    "\003\000\002\004\004\000\002\004\015\000\002\004\013" +
    "\000\002\004\016\000\002\004\005\000\002\004\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\054\000\014\054\012\060\011\063\006\064\005\065" +
    "\007\001\002\000\016\002\056\054\012\060\011\063\006" +
    "\064\005\065\007\001\002\000\002\001\002\000\004\031" +
    "\041\001\002\000\004\035\040\001\002\000\024\002\uffff" +
    "\054\uffff\056\uffff\057\uffff\060\uffff\061\uffff\063\uffff\064" +
    "\uffff\065\uffff\001\002\000\014\054\012\060\011\063\006" +
    "\064\005\065\007\001\002\000\004\055\015\001\002\000" +
    "\004\035\014\001\002\000\024\002\ufffe\054\ufffe\056\ufffe" +
    "\057\ufffe\060\ufffe\061\ufffe\063\ufffe\064\ufffe\065\ufffe\001" +
    "\002\000\004\031\016\001\002\000\002\001\002\000\004" +
    "\032\020\001\002\000\014\054\012\060\011\063\006\064" +
    "\005\065\007\001\002\000\016\054\012\056\022\060\011" +
    "\063\006\064\005\065\007\001\002\000\014\054\012\060" +
    "\011\063\006\064\005\065\007\001\002\000\024\002\001" +
    "\054\001\056\001\057\001\060\001\061\001\063\001\064" +
    "\001\065\001\001\002\000\016\054\012\057\025\060\011" +
    "\063\006\064\005\065\007\001\002\000\004\054\026\001" +
    "\002\000\004\035\027\001\002\000\024\002\ufffd\054\ufffd" +
    "\056\ufffd\057\ufffd\060\ufffd\061\ufffd\063\ufffd\064\ufffd\065" +
    "\ufffd\001\002\000\016\054\012\060\011\061\031\063\006" +
    "\064\005\065\007\001\002\000\004\062\032\001\002\000" +
    "\002\001\002\000\004\057\034\001\002\000\004\057\035" +
    "\001\002\000\004\060\036\001\002\000\004\035\037\001" +
    "\002\000\024\002\ufffc\054\ufffc\056\ufffc\057\ufffc\060\ufffc" +
    "\061\ufffc\063\ufffc\064\ufffc\065\ufffc\001\002\000\024\002" +
    "\ufff9\054\ufff9\056\ufff9\057\ufff9\060\ufff9\061\ufff9\063\ufff9" +
    "\064\ufff9\065\ufff9\001\002\000\002\001\002\000\004\004" +
    "\043\001\002\000\002\001\002\000\004\004\045\001\002" +
    "\000\002\001\002\000\004\032\047\001\002\000\014\054" +
    "\012\060\011\063\006\064\005\065\007\001\002\000\016" +
    "\054\012\057\051\060\011\063\006\064\005\065\007\001" +
    "\002\000\004\063\052\001\002\000\004\035\053\001\002" +
    "\000\024\002\ufffb\054\ufffb\056\ufffb\057\ufffb\060\ufffb\061" +
    "\ufffb\063\ufffb\064\ufffb\065\ufffb\001\002\000\004\035\055" +
    "\001\002\000\024\002\ufffa\054\ufffa\056\ufffa\057\ufffa\060" +
    "\ufffa\061\ufffa\063\ufffa\064\ufffa\065\ufffa\001\002\000\004" +
    "\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\054\000\010\003\003\004\007\005\012\001\001\000" +
    "\006\004\022\005\012\001\001\000\004\005\053\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\003\027\004\007\005\012\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\005\016\001\001\000\002\001\001\000\010\003\020" +
    "\004\007\005\012\001\001\000\006\004\022\005\012\001" +
    "\001\000\010\003\023\004\007\005\012\001\001\000\002" +
    "\001\001\000\006\004\022\005\012\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\004\022" +
    "\005\012\001\001\000\002\001\001\000\004\005\032\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\005\041\001\001\000\002\001\001\000\004\005\043" +
    "\001\001\000\002\001\001\000\004\005\045\001\001\000" +
    "\002\001\001\000\010\003\047\004\007\005\012\001\001" +
    "\000\006\004\022\005\012\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public parser(LexerProyUno s) {
        super(s);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // statement_list ::= statement_list statement 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement_list",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= statement_list EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // statement_list ::= statement 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement_list",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // statement ::= expression ENDL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // statement ::= DECIDE OF LPAREN expression RPAREN statement_list ELSE statement_list END DECIDE ENDL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // statement ::= LOOP statement_list EXIT WHEN expression END END LOOP ENDL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // statement ::= FOR LPAREN expression SEMI expression SEMI expression RPAREN statement_list END FOR ENDL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // statement ::= RETURN expression ENDL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // statement ::= BREAK ENDL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

