
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Dec 25 15:42:13 CST 2025
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHEN = 48;
  public static final int SHOW = 40;
  public static final int POW = 11;
  public static final int STRING_LITERAL = 57;
  public static final int LBRACKET = 25;
  public static final int CHAR = 37;
  public static final int CHAR_LITERAL = 56;
  public static final int GE = 17;
  public static final int LPAREN = 23;
  public static final int SEMI = 2;
  public static final int INT = 34;
  public static final int FOR = 49;
  public static final int MINUS = 6;
  public static final int RPAREN = 24;
  public static final int BOOLEAN_LITERAL = 55;
  public static final int ENDL = 27;
  public static final int NOT = 22;
  public static final int AND = 20;
  public static final int LT = 14;
  public static final int DECIDE = 42;
  public static final int COAL = 30;
  public static final int OR = 21;
  public static final int BOOL = 36;
  public static final int COMMA = 3;
  public static final int GET = 41;
  public static final int NAVIDAD = 29;
  public static final int INC = 12;
  public static final int EXIT = 47;
  public static final int LOOP = 46;
  public static final int PLUS = 5;
  public static final int ASSIGN = 4;
  public static final int LE = 15;
  public static final int OF = 43;
  public static final int EOF = 0;
  public static final int RETURN = 50;
  public static final int RBRACKET = 26;
  public static final int DIV_INT = 8;
  public static final int error = 1;
  public static final int MOD = 10;
  public static final int BREAK = 51;
  public static final int WORLD = 32;
  public static final int VOID = 39;
  public static final int EQ = 18;
  public static final int TIMES = 7;
  public static final int COLON = 28;
  public static final int ELSE = 44;
  public static final int DIV_FLOAT = 9;
  public static final int TO = 52;
  public static final int FLOAT = 35;
  public static final int NE = 19;
  public static final int END = 45;
  public static final int STRING = 38;
  public static final int LOCAL = 33;
  public static final int DEC = 13;
  public static final int FLOAT_LITERAL = 54;
  public static final int GT = 16;
  public static final int GIFT = 31;
  public static final int IDENTIFIER = 58;
  public static final int INTEGER_LITERAL = 53;
}

